/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Users.ReaderManagerText;
import Users.User;
import Users.UserList;
import Users.WriterManagerText;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Kevin Trejos
 */
public class Registro extends javax.swing.JDialog {

    UserList list = new UserList();
    WriterManagerText writer = new WriterManagerText();
    ReaderManagerText reader = new ReaderManagerText();
    boolean ID = false;
    boolean password = false;

    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        closeX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfContraseña = new javax.swing.JPasswordField();
        btnAtras = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Por favor ingrese los datos solicitados");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Ingrese un id");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese una contraseña");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registrarse");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfID)
                            .addComponent(tfContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistro)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnRegistro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

//        verificarID();
//        verificarContraseña();
        if (ID != true && password != true) {
            try {
                if (!list.getUserList().containsUser(tfID.getText())) {
                    User user = new User(tfID.getText(), tfContraseña.getPassword().toString());
                    writer.writerUser(user);
                    System.out.println("Correcto");
                    this.dispose();
                    FrameJuego frame = new FrameJuego();
                    frame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "La id ya está en uso, por favor use otra");
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void verificarID() {
        if (tfID.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "La id no puede tener una extensión menor a 4");
            ID = true;
        } else if (tfID.getText().length() > 6) {
            JOptionPane.showMessageDialog(null, "La id no puede tener una extensión mayor a 6");
            ID = true;
        } else if (quitarNumero(tfID.getText()) < 4) {
            JOptionPane.showMessageDialog(null, "La id no puede tener una extensión menor a 4(no se incluyen los números)");
            ID = true;
        } else if (quitarNumero(tfID.getText()) > 6) {
            JOptionPane.showMessageDialog(null, "La id no puede tener más de 6 caracteres(Sin incluir números)");
            ID = true;
        } else {
            ID = false;
        }
    }

    private void verificarContraseña() {
        if (tfContraseña.getPassword().length < 4 || tfContraseña.getPassword().length > 8) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede tener menos de 4 caracteres ni más de 8");
            password = true;
        } else if (quitarNumero(tfContraseña.getPassword().toString()) < 4) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede tener menos de 4 caracteres(Sin incluir números)");
            password = true;
        } else if (quitarNumero(tfContraseña.getPassword().toString()) > 8) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede tener más de 8 caracteres (Sin incluir números)");
            password = true;
        } else {
            password = false;
        }
    }

//    private boolean compararNombres() throws IOException {
//        UserList list = reader.leer();
//        for (int i = 0; i < list.getCount(); i++) {
//            if (list.containsUser(tfID.getText())) {
//                return true;
//            }
//        }
//        return false;
////        String lista = reader.leerUsers();
////        for (int i = 0; i < lista.length(); i++) {
////            if (lista.contentEquals(tfID.getText())) {
////                return true;
////            }
////        }
////        return false;
//    }

    
    
    private void closeX() {
        try {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    confirm();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean isNumeroOrCharacter(String str) {
        boolean result = false;
        for (int i = 0; i < str.length(); i++) {
            char character = str.charAt(i);
            if (!Character.isLetter(character)) {
                result = true;
                System.out.println("Hola");
            } else {
                result = false;
            }
        }
        return result;
    }

    private int quitarNumero(String str) {
        int count = str.length();
        for (int i = 0; i < str.length(); i++) {
            if (isNumeroOrCharacter(str)) {
                count -= 1;
            }
        }
        return count;
    }

    private void confirm() {
        VentanaPrincipal principal = new VentanaPrincipal();
        this.dispose();
        principal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tfContraseña;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
