/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Hexagon;
import Logic.Logic;
import estructura.HexagonalButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Nacho
 */
public class Tablero extends javax.swing.JFrame {

    private HexagonalButton[][] buttons;
    private int indicadorJugador = 1;
    private int tamaño;
    Logic logic;

    /**
     * Creates new form Tablero
     */
    public Tablero(int tamaño) {
        initComponents();
        logic = new Logic();
        this.tamaño = tamaño;
        setResizable(false);
        if (tamaño == 7) {
            setBounds(0, 0, 700, 500);
        } else if (tamaño == 8) {
            setBounds(0, 0, 750, 600);
        } else if (tamaño == 9) {
            setBounds(0, 0, 800, 600);
        } else if (tamaño == 10) {
            setBounds(0, 0, 850, 600);
        } else if (tamaño == 11) {
            setBounds(0, 0, 940, 650);
        } else if (tamaño == 12) {
            setBounds(0, 0, 990, 670);
        }
        buttons = new HexagonalButton[tamaño + 2][tamaño + 2];
        boardCreation(tamaño + 2);
        initializerActions(tamaño + 2);
    }

        private void initializerActions(int size) {
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                buttons[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        logic.verifyWinPlayer2();
                        logic.verifyWinPlayer1();
                        HexagonalButton clickedButton = (HexagonalButton) e.getSource();
                        Hexagon hexagon = new Hexagon(indicadorJugador, clickedButton.getRow(), clickedButton.getCol());
                        if (indicadorJugador == 1) {
                            clickedButton.changeColor(1);
                            logic.verificationPredecessorJ1(hexagon);
                            logic.addHexagonTreeJ1(hexagon);
                            logic.verifyWinPlayer1();
                            ++indicadorJugador;
                        } else if (indicadorJugador == 2) {
                            clickedButton.changeColor(2);
                            logic.verificationPredecessorJ2(hexagon);
                            logic.addHexagonTreeJ2(hexagon);
                            logic.verifyWinPlayer2();
                            --indicadorJugador;
                        }
                      
                        repaint();
                    }
                });
            }
        }
    }

    private void boardCreation(int size) {
        int xStandard = 63;
        int x = 40;
        int y = 30;
        for (int row = 0; row < size; row++) {
            for (int col = 0; col < size; col++) {
                buttons[row][col] = new HexagonalButton(row - 1, col - 1);
                add(buttons[row][col]);
                buttons[row][col].setBounds(x, y, 56, 56);

                if (row == 0) {
                    buttons[0][col].colorCambiante(1);
                    buttons[0][col].setEnabled(false);
                }
                if (row == (size - 1)) {
                    buttons[(size - 1)][col].colorCambiante(1);
                    buttons[(size - 1)][col].setEnabled(false);
                }
                if (col == 0) {
                    buttons[row][0].colorCambiante(2);
                    buttons[row][0].setEnabled(false);
                }
                if (col == (size - 1)) {
                    buttons[row][(size - 1)].colorCambiante(2);
                    buttons[row][(size - 1)].setEnabled(false);
                }
                x += 45;
            }
            if (row == 0) {
                x = xStandard;
            } else {
                x = xStandard;
                x += 22 * row;
            }
            y += 40;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        Tablero tablero = new Tablero(7);
        tablero.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
